version: 2.1

jobs:
  test:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run:
          name: Run unit tests
          command: python -m unittest discover -s . -p "test_*.py"

workflows:
  version: 2
  test:
    jobs:
      - test